name: analog_timer
description: A beautiful, customizable analog timer widget for Flutter with warning colors, countdown functionality, and smooth animations.
version: 1.0.0
homepage: https://vignaraj.dev
repository: https://github.com/vignarajj/analog_timer
issue_tracker: https://github.com/vignarajj/analog_timer/issues
topics:
  - timer
  - analog
  - countdown
  - widget
  - ui

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0
